import type { Cookie } from './crypto';

/**
 * Netscape HTTP Cookie File Format
 *
 * This format is required by yt-dlp, wget, curl, and other CLI archival tools.
 * The format is very strict - any deviation causes parse failures.
 *
 * @see https://curl.se/docs/http-cookies.html
 * @see https://github.com/yt-dlp/yt-dlp#filesystem-options
 */

/**
 * Header required by yt-dlp and wget to recognize the file format.
 * This exact string is checked by yt-dlp's cookie parser.
 */
const NETSCAPE_HEADER = '# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by Cookie Vault\n\n';

/**
 * Converts a JavaScript boolean to Netscape format.
 * CRITICAL: Must be uppercase TRUE/FALSE - lowercase breaks wget.
 */
function boolToNetscape(value: boolean): string {
  return value ? 'TRUE' : 'FALSE';
}

/**
 * Converts expiration date to Unix epoch in seconds.
 * Chrome API returns seconds, but we verify and handle both cases.
 *
 * @param expirationDate - Timestamp (could be seconds or milliseconds)
 * @param isSession - Whether this is a session cookie
 * @returns Unix timestamp in seconds, or 0 for session cookies
 */
function formatExpiration(expirationDate: number | undefined, isSession?: boolean): string {
  // Session cookies have no expiration
  if (isSession || expirationDate === undefined) {
    return '0';
  }

  // Chrome cookies.expirationDate is in seconds since epoch
  // But if something passes milliseconds (13+ digits), convert it
  let timestamp = expirationDate;
  if (timestamp > 9999999999) {
    // Likely milliseconds, convert to seconds
    timestamp = Math.floor(timestamp / 1000);
  }

  return Math.floor(timestamp).toString();
}

/**
 * Formats the domain column according to Netscape spec.
 *
 * The domain column determines cookie scope:
 * - Leading dot (.example.com) = include subdomains
 * - No dot (example.com) = exact host match only
 *
 * Chrome's hostOnly property maps to this:
 * - hostOnly=true → no leading dot (exact match)
 * - hostOnly=false → leading dot (include subdomains)
 */
function formatDomain(domain: string, hostOnly?: boolean): string {
  const hasDot = domain.startsWith('.');

  if (hostOnly) {
    // Exact host match - remove leading dot if present
    return hasDot ? domain.slice(1) : domain;
  } else {
    // Include subdomains - ensure leading dot
    return hasDot ? domain : `.${domain}`;
  }
}

/**
 * Determines the subdomain inclusion flag.
 * TRUE if cookie applies to subdomains, FALSE for exact host only.
 */
function formatSubdomainFlag(_domain: string, hostOnly?: boolean): string {
  if (hostOnly) {
    return 'FALSE';
  }
  return 'TRUE';
}

/**
 * Formats a single cookie as a Netscape line.
 *
 * Format: domain<TAB>flag<TAB>path<TAB>secure<TAB>expiration<TAB>name<TAB>value
 *
 * @param cookie - The cookie to format
 * @returns Tab-separated line (no trailing newline)
 */
function formatCookieLine(cookie: Cookie): string {
  const domain = formatDomain(cookie.domain, cookie.hostOnly);
  const flag = formatSubdomainFlag(cookie.domain, cookie.hostOnly);
  const path = cookie.path || '/';
  const secure = boolToNetscape(cookie.secure);
  const expiration = formatExpiration(cookie.expirationDate, cookie.session);
  const name = cookie.name;
  const value = cookie.value;

  return `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}`;
}

/**
 * Formats an array of cookies as a complete Netscape HTTP Cookie File.
 *
 * This format is compatible with:
 * - yt-dlp (--cookies option)
 * - gallery-dl (--cookies option)
 * - wget (--load-cookies option)
 * - curl (--cookie option)
 * - aria2c (--load-cookies option)
 *
 * @param cookies - Array of cookies to format
 * @returns Complete file content with header
 */
export function formatNetscape(cookies: Cookie[]): string {
  const lines = cookies.map(formatCookieLine);
  return NETSCAPE_HEADER + lines.join('\n') + '\n';
}

/**
 * Formats cookies for a specific domain only.
 * Useful for exporting just the active tab's cookies.
 *
 * @param cookies - Array of all cookies
 * @param domain - Target domain to filter
 * @returns Netscape file content for matching cookies
 */
export function formatNetscapeForDomain(cookies: Cookie[], domain: string): string {
  // Normalize the target domain
  const normalizedTarget = domain.toLowerCase().replace(/^\./, '');

  const filtered = cookies.filter((cookie) => {
    const cookieDomain = cookie.domain.toLowerCase().replace(/^\./, '');

    // Exact match
    if (cookieDomain === normalizedTarget) {
      return true;
    }

    // Subdomain match (cookie domain is parent of target)
    if (normalizedTarget.endsWith(`.${cookieDomain}`)) {
      return true;
    }

    // Parent match (target is parent of cookie domain)
    if (cookieDomain.endsWith(`.${normalizedTarget}`)) {
      return true;
    }

    return false;
  });

  return formatNetscape(filtered);
}

/**
 * Downloads a Netscape cookie file.
 *
 * @param cookies - Cookies to export
 * @param filename - Optional filename (defaults to cookies.txt)
 */
export async function downloadNetscape(
  cookies: Cookie[],
  filename: string = 'cookies.txt'
): Promise<void> {
  const content = formatNetscape(cookies);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);

  if (typeof chrome !== 'undefined' && chrome.downloads) {
    await chrome.downloads.download({
      url: url,
      filename: filename,
      saveAs: true,
    });
  } else {
    // Fallback for non-extension environment
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
  }

  URL.revokeObjectURL(url);
}
